### ISSUE TITLE
License

### ISSUE THREAD

**Issue by RichardLitt** [BayesForDays/dissertation#1]
What license is this under? :)

**Comment by BayesForDays** [comment]
Do you have suggestions? They're whatever academics can use for their own research -- I think for various reasons related to licenses with LDC/COCA/etc. The materials are the exact same as my dissertation tables, [which is already public and hosted on IDEALS](https://www.ideals.illinois.edu/handle/2142/97364).

**Comment by RichardLitt** [comment]
I would suggest a Creative Commons license then! You can learn more, here: https://creativecommons.org/licenses/by-sa/4.0/
